from setuptools import setup, find_packages

setup(
    name="lfft",
    version="0.1.0",
    author="Author",
    author_email="author@example.com",
    description="Logic Feedback Fusion Technology for Presentation Generation",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/username/lfft",
    packages=find_packages(),
    include_package_data=True,
    package_data={
        "lfft": ["resource/prompts/*.txt", "resource/roles/*.yaml"],
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.25.0",
        "python-pptx>=1.0.3",
        "pillow>=9.0.0",
        "numpy>=1.20.0",
        "pandas>=1.3.0",
        "pydantic>=2.0.0",
        "jinja2>=3.0.0",
        "tqdm>=4.45.0",
        "openai>=1.0.0",
        "tenacity>=8.0.0",
        "tiktoken>=0.5.0",
        "mistune>=2.0.0",
        "lxml>=4.6.0",
        "bs4>=0.0.1",
        "jsonlines>=1.2.0",
        "json-repair>=0.0.1",
        "Levenshtein>=0.20.0",
        "html2image>=2.0.0",
        "pdf2image>=1.16.0",
        "scikit-learn>=1.0.0",
    ],
)